name: gymapp
description: Gym App
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/

  fonts:
  - family: AppIcons
    fonts:
    - asset: assets/fonts/app_icons.ttf
