name: Continous Integration
on:
  push:
    branches: [ master ]
    paths:
      - '**.dart'
  pull_request:
    branches: [ master ]
    paths:
      - '**.dart'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:  
    - uses: actions/checkout@v1

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '2.5.x'

    - run: dart --version
    - run: flutter --version

    - name: Install app dependencies
      run: flutter pub get

    - name: Test app
      run: flutter test --coverage

    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
    #  with:
    #    token: ${{ secrets.CODECOV_TOKEN }}
    #    file: coverage/lcov.info
